# Generated by Django 3.0 on 2020-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matches_between_teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='points_between_teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('winner_of_match', models.CharField(max_length=100)),
                ('points_of_team', models.IntegerField()),
                ('total_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pointstable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('match', models.IntegerField()),
                ('won', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('n_r', models.IntegerField()),
                ('points', models.IntegerField()),
                ('nrr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='structure_of_players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('jersy_number', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('total_matches', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('highest_score', models.IntegerField()),
                ('fiftys', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('man_of_the_matches', models.IntegerField()),
                ('winner_of_matches', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='pics')),
                ('flag', models.FileField(blank=True, null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='struture_of_teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='pics')),
                ('club_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userregistrationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
